<?php
/**
 * $this Favizone_Recommender_Block_Adminhtml_Wizard
 */
?>
<?php if (!Mage::app()->isSingleStoreMode()): ?>
    <?php echo $this->getChildHtml('store_switcher'); ?>
<?php endif;?>
<div class="container-fluid">
    <?php if ($this->isAccessKeyLoaded() ): ?>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body text-center">
                    <div class="row-fluid">
                        <div class="content-block">
                            <div class="content-panel">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="login-block">
                                            <a target="_blank" href="http://www.favizone.com/support" class="pull-right">
                                                <i class="fa fa-question-circle" ></i>  <?php echo $this->__('Help');?>
                                            </a>
                                            <img class="img-logo" src="<?php echo $this->getSkinUrl('images/favizone/logo-favizone.png')?>">
                                            <div id="favizone_success_update" class="alert alert-success hide" role="alert">
                                               <?php echo $this->__('Data successfully updated.');?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="content-block">
                            <div class="content-panel">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div  class="col-md-12">
                                                <div id="submit-step-2" class="hide">
                                                    <p><i class="fa fa-spinner fa-pulse fa-5x"></i></p>
                                                    <h1><?php echo $this->__('Please wait ...');?></h1>
                                                </div>
                                                <div id="submit-step-final" class="hide">
                                                    <p><i class="fa fa-check  fa-5x"></i></p>
                                                    <h1><?php echo $this->__('Analysis done!');?></h1>
                                                    <h2><?php echo $this->__('Your shop categories were synchronized');?></h2>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <form id="submit-ab-test"  method="post" onsubmit="return sendData('<?php echo $this->getUrl('*/*/updateAbTesting', array('isAjax' => true))?>', 'submit-ab-test', <?php echo Favizone_Recommender_Block_Common::getSelectedStore()->getId(); ?>);">
                                                <div class="form-group">
                                                    <label for="ab_test" class="help-block col-lg-5 ">
                                                       <?php echo $this->__('Enable A/B Testing');?> </label>
                                                    <div class="col-lg-3 ">
                                                <span class="switch prestashop-switch fixed-width-lg">
                                                    <?php if ($this->getAbTest()=="true") { ?>
                                                        <input type="radio" name="ab_test" id="ab_test_on" value="true" checked="checked" />
                                                    <?php } else { ?>
                                                        <input type="radio" name="ab_test" id="ab_test_on" value="true"  />
                                                    <?php } ?>
                                                    <label for="ab_test_on"> <?php echo $this->__('Yes');?>  </label>

                                                    <?php if ($this->getAbTest()=="false") { ?>
                                                        <input type="radio" name="ab_test" id="ab_test_off" value="false" checked="checked" />
                                                    <?php } else { ?>
                                                        <input type="radio" name="ab_test" id="ab_test_off" value="false"  />
                                                    <?php } ?>
                                                    <label for="ab_test_off"> <?php echo $this->__('No');?>   </label>
                                                <a class="slide-button btn"></a>
                                                </span>
                                                    </div>
                                                    <div class="col-lg-2">
                                                        <button name="submitRecommandor" class="btn btn-default" type="submit">
                                                            <i class="fa fa-check"></i>
                                                           <?php echo $this->__('Submit');?>
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-4 ">
                                                <p>
                                                    <a class="btn"  target="_blank" href="<?php echo Mage::helper('favizone_recommender/data')->getHost();?>/dashboard/index" ><i class="fa fa-bar-chart fa-2x"></i>  <?php echo $this->__('View my statistics');?> </a>
                                                </p>
                                            </div>
                                            <div class="col-md-4 ">
                                                <p>
                                                    <a class="btn" target="_blank" href="<?php echo Mage::helper('favizone_recommender/data')->getHost();?>/profil"  ><i class="fa fa-user fa-2x"></i>
                                                        <?php echo $this->__('Go to my profile');?> </a>
                                                </p>
                                            </div>
                                            <div class="col-md-4 ">
                                                <p>
                                                    <a class="btn" onclick="sendData('<?php echo $this->getUrl('*/*/sendCategoryData', array('isAjax' => true))?>', 'category-sync', <?php echo Favizone_Recommender_Block_Common::getSelectedStore()->getId(); ?>);" name="submitFavizoneCategories"><i class="fa fa-refresh fa-2x"></i><?php echo $this->__('Synchronize my categories'); ?> </a>
                                                </p>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php else:?>
        <?php $params = array('isAjax' => true);
              $url =  $this->getUrl('*/*/synchronizeData',  $params);
        ?>
        <div class="row">
            <form id="submit-form"  onsubmit="return sendData('<?php echo $url ?>', 'submit-register',<?php echo Favizone_Recommender_Block_Common::getSelectedStore()->getId(); ?>);" >
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <div class="row-fluid">
                            <div class="">
                                <div class="content-block">
                                    <div class="content-panel">
                                        <div class="panel panel-default">
                                            <div class="panel-body">
                                                <div class="login-block">
                                                    <a target="_blank" href="http://www.favizone.com/support" class="pull-right">
                                                        <i class="fa fa-question-circle" ></i>  <?php echo $this->__('Help');?>
                                                    </a>
                                                    <img class="img-logo" src="<?php echo $this->getSkinUrl('images/favizone/logo-favizone.png')?>">
                                                    <div id="submit-step-1" class="">
                                                        <h2 class="h4 content-header"> <?php echo $this->__('Please add your email');?></h2>
                                                        <div class="panes">
                                                            <div>
                                                                <div class="form-group">
                                                                    <input type="email"  id="auth_key" name="auth_key"  required placeholder=" <?php echo $this->__('Your email');?>">
                                                                    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" />
                                                                </div>
                                                                <button  class="btn  btn-default btn-blue"  type="submit" name="submitfavizone">
                                                                    <i class="fa fa-check"></i> <?php echo $this->__('Submit'); ?>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div id="submit-step-2" class="hide">
                                                        <p><i class="fa fa-spinner fa-pulse fa-5x"></i></p>
                                                        <h1><?php echo $this->__('Please wait ...');?></h1>
                                                    </div>
                                                    <div id="submit-step-final" class="hide">
                                                        <p><i class="fa fa-check  fa-5x"></i></p>
                                                        <h1><?php echo $this->__('Analysis done!');?></h1>
                                                        <h2><?php echo $this->__('Your shop data were analyzed') ;?></h2>
                                                        <h3><a href="http://www.favizone.com/support" target="_blank"><?php echo $this->__('Help to getting stared') ;?></a></h3>
                                                    </div>
                                                    <div id="submit-step-final-error" class="hide">
                                                        <p><i class="fa fa-close  fa-5x"></i></p>
                                                        <h1><?php echo $this->__('Error! Please refresh the the page and try again');?></h1>
                                                        <p><?php echo $this->__('You can contact our support for any information :') ;?><a href="mailto:support@favizone.com">support@favizone.com</a></p>
                                                    </div>
                                                    <p>
                                                        <label>
                                                            <i class="fa fa-exclamation"></i>
                                                            <?php echo $this->__('Note : installing Favizone  will not activate immediately the recommendations on your site') ;?>
                                                        </label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <p class="terms-block">
                                            <?php echo $this->__('By clicking you accept the') ;?>    <a target="_blank" href="www.favizone.com/terms">   <?php echo $this->__('the terms and conditions of Favizone') ;?>  </a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    <?php endif;?>
</div>
